"""
CASAScriptGenerator — CASA script generation for Quasar AI
Generates imaging scripts (and, for non-ALMA or explicitly forced cases,
manual calibration scripts) for radio interferometry data reduction.

ALMA reality (skill guardrail 4, products-and-qa.md "Getting a calibrated
MeasurementSet"): ALMA archive data are PIPELINE-calibrated. The delivered
package holds caltables + scripts + QA + selected FITS products but NO
calibrated MeasurementSet; the MS is RESTORED with the package's own
``scriptForPI.py`` under the CASA/pipeline version stated in the QA2 report,
README, weblog or manifest (or obtained from an ARC / NRAO SRDP calibrated-MS
service). A generic manual calibration recipe is the rare exception
(per-EB ``*.scriptForCalibration.py`` for legacy/manual datasets), so for
ALMA this generator refuses to emit one unless ``force_manual=True`` and
instead returns the restore guidance (INT-7, report A-17/A-32).

Registered agent tools:
    - generate_casa_imaging_script(params)
    - generate_casa_calibration_script(params)
"""

import json
from typing import Optional, Dict, Any, List


ALMA_RESTORE_GUIDANCE: Dict[str, Any] = {
    "summary": (
        "ALMA archive data are pipeline-calibrated. The standard delivery contains NO calibrated "
        "MeasurementSet; restore it with the package's scriptForPI.py under the matching CASA "
        "version, or request calibrated visibilities from an ARC / NRAO SRDP."
    ),
    "steps": [
        "Enumerate the MOUS with list_alma_files: download the *_auxiliary.tar (scripts, caltables, "
        "flagversions, QA reports, README) and the RAW ASDMs (*uid___A002_*.asdm.sdm.tar, one per "
        "execution block) named by the package's restore script/manifest/PPR. The numbered FITS "
        "product tars are science products and are not needed for the restore.",
        "Read the CASA + pipeline version in the QA2 report / README / weblog / pipeline_manifest.xml. "
        "Use that version for identical reproduction, or a release the current ALMA compatibility "
        "table (https://almascience.nrao.edu/processing/science-pipeline) authorizes. Never infer the "
        "version from the proposal cycle.",
        "Stage the ASA tree intact (raw/ beside script/, calibration/, qa/ inside member.uid___*/), "
        "inspect the package Python, confirm exactly one scriptForPI.py belongs to that MOUS, then from "
        "its script/ directory run: casa --pipeline -c scriptForPI.py",
        "Output lands in calibrated/ (per-EB uid___*.ms with CORRECTED_DATA, or calibrated/working/; "
        "older cycles: uid___*.ms.split.cal). Budget roughly 6x (SPACESAVING=3) to 14x "
        "(SPACESAVING=0) the size of products + raw data as working space.",
        "Alternative: the ARCs and NRAO SRDP provide calibrated-MS services for much public "
        "pipeline-reduced Cycle 5+ 12-m/ACA data (no manual/TP data; no selfcal or continuum "
        "subtraction) — check the current official guidance before relying on coverage.",
    ],
    "manual_exception": (
        "Manually calibrated datasets (common through ~Cycle 3, dataset-dependent later) ship per-EB "
        "*.scriptForCalibration.py scripts driven by scriptForPI under the era-appropriate CASA; "
        "even then, run the delivered scripts rather than a generic recipe."
    ),
    "reference": "browse_alma_guidance(topic='products-qa-restore')",
}


# Templates for common CASA tasks
IMAGING_TEMPLATE = """
# ============================================================
# CASA Imaging Script — Generated by Quasar AI
# Target: {target}
# Band: {band} | Configuration: {config}
# ------------------------------------------------------------
# PREREQUISITE: `vis` must be a CALIBRATED MeasurementSet. ALMA archive
# packages do NOT contain one — restore it first with the package's
# scriptForPI.py under the CASA version stated in the QA2 report/README
# (output: calibrated/uid___*.ms), or obtain calibrated visibilities from
# an ARC / NRAO SRDP. Do not re-flag the pipeline-calibrated MS here.
# ============================================================
import os

# ── User Parameters ──────────────────────────────────────────
target       = '{target}'
vis          = '{vis}'          # Calibrated measurement set path
imagename    = '{imagename}'    # Output image base name
datacolumn   = '{datacolumn}'   # 'corrected' if CORRECTED_DATA exists (check tb.colnames()), else 'data'
spw          = '{spw}'          # SPW selection ('' = all; for mfs continuum consider cont.dat ranges / uvcontsub)
cell         = '{cell}'         # Cell size (e.g., '0.02arcsec')
imsize       = {imsize}         # Image size in pixels [nx, ny]
weighting    = '{weighting}'    # 'natural', 'uniform', or 'briggs'
robust       = {robust}         # Briggs robust parameter (-2 to +2)
niter        = {niter}          # Max clean iterations
threshold    = '{threshold}'    # Clean threshold (e.g., '0.1mJy')
deconvolver  = '{deconvolver}'  # 'hogbom', 'clark', 'multiscale', 'mtmfs'
specmode     = '{specmode}'     # 'mfs' or 'cube'

# ── Pre-imaging checks ────────────────────────────────────────
print(f"[QUASAR] Starting imaging for {{target}}")
os.makedirs(os.path.dirname(imagename) or '.', exist_ok=True)
listobs(vis=vis, listfile=imagename + '.listobs.txt', overwrite=True)

# ── Run tclean ───────────────────────────────────────────────
tclean(
    vis=vis,
    imagename=imagename,
    field=target,
    spw=spw,
    datacolumn=datacolumn,
    cell=cell,
    imsize=imsize,
    specmode=specmode,
    deconvolver=deconvolver,
    weighting=weighting,
    robust=robust,
    niter=niter,
    threshold=threshold,
    interactive=False,
    savemodel='none',
    pbcor=True,
)

# ── Export to FITS ────────────────────────────────────────────
for suffix in ['.image', '.image.pbcor', '.pb', '.residual', '.model', '.psf']:
    img = imagename + suffix
    if os.path.exists(img):
        exportfits(imagename=img, fitsimage=img + '.fits', overwrite=True)
        print(f"[QUASAR] Exported: {{img}}.fits")

print("[QUASAR] Imaging complete!")
"""

# Manual calibration for VLA-style data (a priori steps of ALMA are NOT here).
VLA_CALIBRATION_TEMPLATE = """
# ============================================================
# CASA Manual Calibration Script (VLA-style) — Generated by Quasar AI
# Target: {target} | Flux Cal: {flux_cal} | Phase Cal: {phase_cal}
# ============================================================

vis              = '{vis}'
flux_calibrator  = '{flux_cal}'
phase_calibrator = '{phase_cal}'
target           = '{target}'
refant           = '{refant}'       # Reference antenna (e.g., 'ea10')
spw              = '{spw}'          # Spectral window (e.g., '0,1,2,3')

print("[QUASAR] Starting manual (VLA-style) calibration")

# ── Flagging ─────────────────────────────────────────────────
flagdata(vis=vis, mode='manual', autocorr=True)
flagdata(vis=vis, mode='shadow')
flagdata(vis=vis, mode='tfcrop', flagbackup=True)

# ── Set flux model for the flux calibrator ───────────────────
# Perley-Butler is the VLA catalogue standard for 3C286/3C48/3C147/3C138;
# 'Butler-JPL-Horizons' applies ONLY to solar-system bodies.
setjy(vis=vis, field=flux_calibrator, standard='Perley-Butler 2017')

# ── Delay calibration ─────────────────────────────────────────
gaincal(
    vis=vis, caltable='delay.cal', field=flux_calibrator,
    refant=refant, gaintype='K', solint='inf'
)

# ── Bandpass calibration ─────────────────────────────────────
bandpass(
    vis=vis, caltable='bandpass.cal', field=flux_calibrator,
    refant=refant, solint='inf', gaintable=['delay.cal']
)

# ── Phase calibration ─────────────────────────────────────────
gaincal(
    vis=vis, caltable='phase.cal', field=phase_calibrator,
    refant=refant, gaintype='G', solint='int', calmode='p',
    gaintable=['delay.cal', 'bandpass.cal']
)

# ── Amplitude calibration ─────────────────────────────────────
gaincal(
    vis=vis, caltable='amp.cal', field=phase_calibrator,
    refant=refant, gaintype='G', solint='inf', calmode='a',
    gaintable=['delay.cal', 'bandpass.cal', 'phase.cal']
)

# ── Flux scaling ──────────────────────────────────────────────
fluxscale(
    vis=vis, caltable='amp.cal', fluxtable='flux.cal',
    reference=flux_calibrator
)

# ── Apply calibrations to target ─────────────────────────────
applycal(
    vis=vis, field=target, calwt=False,
    gaintable=['delay.cal', 'bandpass.cal', 'phase.cal', 'flux.cal']
)

# ── Split calibrated target data ─────────────────────────────
split(vis=vis, outputvis='{target}_calibrated.ms', field=target, datacolumn='corrected')

print("[QUASAR] Calibration complete! Output: {target}_calibrated.ms")
"""

# Bespoke manual calibration for ALMA (ONLY when force_manual=True): mirrors
# the a priori steps a scriptForCalibration performs — Tsys, WVR, antenna
# positions — before bandpass/gain, with the catalogue flux model (not a
# solar-system standard) and ALMA's calwt=True convention.
ALMA_MANUAL_CALIBRATION_TEMPLATE = """
# ============================================================
# CASA MANUAL Calibration Script for ALMA — Generated by Quasar AI
# Target: {target} | Flux Cal: {flux_cal} | Phase Cal: {phase_cal}
# ------------------------------------------------------------
# WARNING: ALMA archive data are pipeline-calibrated. Prefer restoring the
# delivered calibration with scriptForPI.py (casa --pipeline -c scriptForPI.py)
# under the CASA version in the QA2 report. This bespoke recipe is for
# legacy/commissioning data or a deliberate re-reduction, and it OMITS the
# per-dataset flag templates, renormalization and QA checks the pipeline
# applies. Run it per execution block (per ASDM -> MS).
# ============================================================

vis              = '{vis}'          # importasdm output for ONE execution block
flux_calibrator  = '{flux_cal}'     # quasar (J...) or solar-system body
phase_calibrator = '{phase_cal}'
target           = '{target}'
refant           = '{refant}'       # e.g. 'DA41'
spw              = '{spw}'          # science SPWs (e.g. '16,18,20,22'); WVR/CH_AVG/SQLD SPWs excluded
flux_is_solar_system = {flux_is_solar_system}  # True only for planets/moons/asteroids

print("[QUASAR] Starting MANUAL ALMA calibration (a priori + bandpass + gain)")

# ── A priori calibration ─────────────────────────────────────
gencal(vis=vis, caltable='tsys.cal', caltype='tsys')                 # system temperature
wvrgcal(vis=vis, caltable='wvr.cal', toffset=0, spw=[int(s) for s in spw.split(',') if s])  # WVR phase correction
gencal(vis=vis, caltable='antpos.cal', caltype='antpos', antenna='')  # antenna position corrections (fill from the ALMA antpos service)

# ── Flagging ─────────────────────────────────────────────────
flagdata(vis=vis, mode='manual', autocorr=True, flagbackup=True)
flagdata(vis=vis, mode='shadow', tolerance=0.0)
flagdata(vis=vis, mode='manual', intent='*POINTING*,*ATMOSPHERE*,*SIDEBAND_RATIO*')

# ── Flux model ───────────────────────────────────────────────
if flux_is_solar_system:
    setjy(vis=vis, field=flux_calibrator, standard='Butler-JPL-Horizons 2012')
else:
    # Quasar flux calibrator: use the ALMA Calibrator Source Catalogue value
    # at the observing frequency (fluxdensity=[I,Q,U,V], spix, reffreq).
    setjy(vis=vis, field=flux_calibrator, standard='manual',
          fluxdensity=[{flux_jy}, 0, 0, 0], spix={spix}, reffreq='{reffreq}')

# ── Bandpass calibration ─────────────────────────────────────
gaincal(vis=vis, caltable='bpphase.cal', field=flux_calibrator, spw=spw, refant=refant,
        gaintype='G', solint='int', calmode='p',
        gaintable=['tsys.cal', 'wvr.cal', 'antpos.cal'])
bandpass(vis=vis, caltable='bandpass.cal', field=flux_calibrator, spw=spw, refant=refant,
         solint='inf', combine='scan', solnorm=True,
         gaintable=['tsys.cal', 'wvr.cal', 'antpos.cal', 'bpphase.cal'])

# ── Gain calibration ─────────────────────────────────────────
gaincal(vis=vis, caltable='phase_int.cal', field=flux_calibrator + ',' + phase_calibrator, spw=spw,
        refant=refant, gaintype='G', solint='int', calmode='p',
        gaintable=['tsys.cal', 'wvr.cal', 'antpos.cal', 'bandpass.cal'])
gaincal(vis=vis, caltable='amp.cal', field=flux_calibrator + ',' + phase_calibrator, spw=spw,
        refant=refant, gaintype='T', solint='inf', calmode='ap',
        gaintable=['tsys.cal', 'wvr.cal', 'antpos.cal', 'bandpass.cal', 'phase_int.cal'])
fluxscale(vis=vis, caltable='amp.cal', fluxtable='flux.cal', reference=flux_calibrator)

# ── Apply (ALMA convention: calwt=True so Tsys weights propagate) ─
applycal(vis=vis, field=target, spw=spw, calwt=True,
         gaintable=['tsys.cal', 'wvr.cal', 'antpos.cal', 'bandpass.cal', 'phase_int.cal', 'flux.cal'],
         interp=['linear,linear', 'linear', 'linear', 'linear,linearflag', 'linear', 'linear'])

split(vis=vis, outputvis='{target}_calibrated.ms', field=target, spw=spw, datacolumn='corrected')
print("[QUASAR] Manual ALMA calibration complete! Output: {target}_calibrated.ms")
"""


def _is_alma(telescope: Optional[str]) -> bool:
    return str(telescope or "ALMA").strip().upper() in {"ALMA", "ACA", ""}


class CASAScriptGenerator:
    """Generate CASA data reduction scripts from observation parameters."""

    def generate_casa_imaging_script(
        self,
        target: str,
        vis: str,
        band: str = "6",
        cell: str = "0.02arcsec",
        imsize: int = 1024,
        weighting: str = "briggs",
        robust: float = 0.5,
        niter: int = 10000,
        threshold: str = "0.1mJy",
        specmode: str = "mfs",
        deconvolver: str = "hogbom",
        imagename: Optional[str] = None,
        config: str = "C-5",
        datacolumn: str = "corrected",
        spw: str = "",
    ) -> Dict[str, Any]:
        """
        Generate a CASA tclean imaging script for a CALIBRATED (restored) MS.

        Args:
            target: Target source name (used in field selection)
            vis: Path to the calibrated / restored Measurement Set (.ms)
            band: ALMA band number (string, e.g. '6')
            cell: Cell size (e.g. '0.02arcsec')
            imsize: Square image size in pixels
            weighting: Visibility weighting ('briggs', 'natural', 'uniform')
            robust: Briggs robust parameter (-2 to +2, 0.5 = default)
            niter: Maximum clean iterations
            threshold: Clean stopping threshold (e.g. '0.1mJy')
            specmode: 'mfs' for continuum, 'cube' for line
            deconvolver: 'hogbom', 'clark', 'multiscale', or 'mtmfs'
            imagename: Output image name (auto-derived if None)
            config: ALMA array configuration (for documentation)
            datacolumn: 'corrected' (restored MS) or 'data' (split-out MS)
            spw: SPW selection ('' = all)

        Returns:
            dict with 'script' containing the CASA Python code
        """
        try:
            img_name = imagename or f"images/{target.replace(' ', '_')}_Band{band}"
            script = IMAGING_TEMPLATE.format(
                target=target,
                vis=vis,
                band=band,
                config=config,
                cell=cell,
                imsize=[imsize, imsize],
                weighting=weighting,
                robust=robust,
                niter=niter,
                threshold=threshold,
                specmode=specmode,
                deconvolver=deconvolver,
                imagename=img_name,
                datacolumn=datacolumn,
                spw=spw or "",
            )

            return {
                "success": True,
                "script_type": "casa_imaging",
                "target": target,
                "band": band,
                "script": script,
                "usage": "Save this as `imaging.py` and run in CASA: `execfile('imaging.py')`",
                "prerequisite": (
                    "A calibrated MS. ALMA packages ship none: restore with scriptForPI.py under the "
                    "package's CASA version (see restore_guidance) or use an ARC/SRDP calibrated-MS service."
                ),
                "restore_guidance": ALMA_RESTORE_GUIDANCE,
                "notes": [
                    f"Cell size {cell} should be ~1/5 of your synthesized beam.",
                    f"Imsize {imsize}px should be at least 3x your primary beam FWHM.",
                    f"Threshold {threshold} is ~3-5σ of expected RMS noise.",
                    "Run `listobs(vis=vis)` first to confirm field names and SPW IDs; filename SPW "
                    "numbers in delivered products are pipeline virtual IDs, not the PI's ordinal windows.",
                    "Check tb.colnames() for CORRECTED_DATA before choosing datacolumn; a split-out MS "
                    "usually has only DATA.",
                    "For mfs continuum, exclude line channels (cont.dat from the auxiliary package or "
                    "uvcontsub) — imaging all SPWs together includes them.",
                    "Pipeline products are typically LSRK; native ALMA visibilities are TOPO per EB "
                    "(Doppler setting) — combine EBs only after regridding.",
                ]
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    def generate_casa_calibration_script(
        self,
        target: str,
        vis: str,
        flux_cal: str,
        phase_cal: str,
        refant: str,
        spw: str = "",
        telescope: str = "ALMA",
        force_manual: bool = False,
        flux_is_solar_system: bool = False,
        flux_jy: float = 1.0,
        spix: float = -0.6,
        reffreq: str = "230GHz",
    ) -> Dict[str, Any]:
        """
        Generate a manual calibration script — or, for ALMA, the restore guidance.

        Args:
            target: Science target name
            vis: Input Measurement Set path
            flux_cal: Flux calibrator field name (e.g., 'J1517-2422')
            phase_cal: Phase calibrator field name
            refant: Reference antenna name (e.g., 'DA41')
            spw: Spectral window selection (empty = all)
            telescope: 'ALMA' (default) or 'VLA'
            force_manual: For ALMA, emit a bespoke manual recipe instead of the
                restore guidance (legacy/commissioning data or deliberate re-reduction)
            flux_is_solar_system: ALMA manual recipe — flux calibrator is a planet/moon
            flux_jy, spix, reffreq: ALMA manual recipe — catalogue flux model for a quasar calibrator

        Returns:
            dict with 'script' containing the CASA calibration code, or for ALMA
            without force_manual a success=False dict carrying restore_guidance.
        """
        try:
            safe_target = target.replace(" ", "_")
            if _is_alma(telescope) and not force_manual:
                return {
                    "success": False,
                    "script_type": "casa_calibration",
                    "target": target,
                    "error": (
                        "Manual calibration script NOT generated: ALMA archive data are pipeline-"
                        "calibrated and the delivery contains no calibrated MS. Restore it with the "
                        "package's scriptForPI.py (see restore_guidance) or request calibrated "
                        "visibilities from an ARC/NRAO SRDP. A generic manual recipe would discard the "
                        "delivered caltables, flag templates and QA2 assessment."
                    ),
                    "restore_guidance": ALMA_RESTORE_GUIDANCE,
                    "hint": (
                        "If this is legacy/commissioning data with per-EB scriptForCalibration.py "
                        "scripts, run THOSE. Only for a deliberate bespoke re-reduction call again with "
                        "force_manual=true (the recipe then includes Tsys/WVR/antpos a priori steps and "
                        "a catalogue flux model — never a solar-system standard on a quasar)."
                    ),
                }

            if _is_alma(telescope):
                script = ALMA_MANUAL_CALIBRATION_TEMPLATE.format(
                    target=target, vis=vis, flux_cal=flux_cal, phase_cal=phase_cal,
                    refant=refant, spw=spw or "",
                    flux_is_solar_system=bool(flux_is_solar_system),
                    flux_jy=float(flux_jy), spix=float(spix), reffreq=reffreq,
                ).replace("{target}_calibrated", f"{safe_target}_calibrated")
                notes = [
                    "This is a BESPOKE manual recipe (force_manual=true): the ALMA pipeline restore "
                    "(scriptForPI.py) remains the reference reduction.",
                    "Run per execution block after importasdm; exclude WVR/CH_AVG/SQLD SPWs from `spw`.",
                    "Fill the antenna-position corrections from the ALMA antpos service (or the "
                    "delivered antpos caltable) before gencal(caltype='antpos').",
                    "Quasar flux calibrators need the ALMA Calibrator Source Catalogue value at the "
                    "observing frequency; 'Butler-JPL-Horizons' is only for solar-system bodies.",
                    "ALMA applycal convention is calwt=True (Tsys-based weights).",
                    "Check caltables with plotms before applying; compare against the delivered weblog.",
                ]
                script_type = "casa_calibration_alma_manual"
            else:
                script = VLA_CALIBRATION_TEMPLATE.format(
                    target=target, vis=vis, flux_cal=flux_cal, phase_cal=phase_cal,
                    refant=refant, spw=spw or "",
                ).replace("{target}_calibrated", f"{safe_target}_calibrated")
                notes = [
                    "Run `listobs` first to find the correct field names.",
                    f"Verify reference antenna `{refant}` is central and well-behaved.",
                    "Check calibration tables with `plotms` before applying.",
                    "For VLA data, the NRAO CASA pipeline (or SRDP) is the reference calibration; "
                    "this manual recipe is a starting point for bespoke reductions.",
                ]
                script_type = "casa_calibration"

            return {
                "success": True,
                "script_type": script_type,
                "telescope": "ALMA" if _is_alma(telescope) else str(telescope).upper(),
                "target": target,
                "flux_calibrator": flux_cal,
                "phase_calibrator": phase_cal,
                "script": script,
                "usage": "Save as `calibrate.py` and run in CASA: `execfile('calibrate.py')`",
                "notes": notes,
            }
        except Exception as e:
            return {"success": False, "error": str(e)}
