"""
CASAScriptGenerator — Automatic CASA pipeline script generation for Quasar AI
Generates calibration and imaging scripts for ALMA/VLA data reduction using CASA.

This tool uses the LLM to generate valid CASA Python scripts based on
observation parameters provided by the user, following ALMA pipeline best practices.

Registered agent tools:
    - generate_casa_imaging_script(params)
    - generate_casa_calibration_script(params)
"""

import json
from typing import Optional, Dict, Any, List


# Templates for common CASA tasks
IMAGING_TEMPLATE = """
# ============================================================
# CASA Imaging Script — Generated by Quasar AI
# Target: {target}
# Band: {band} | Configuration: {config}
# ============================================================
import os

# ── User Parameters ──────────────────────────────────────────
target       = '{target}'
vis          = '{vis}'          # Measurement set path
imagename    = '{imagename}'    # Output image base name
cell         = '{cell}'         # Cell size (e.g., '0.02arcsec')
imsize       = {imsize}         # Image size in pixels [nx, ny]
weighting    = '{weighting}'    # 'natural', 'uniform', or 'briggs'
robust       = {robust}         # Briggs robust parameter (-2 to +2)
niter        = {niter}          # Max clean iterations
threshold    = '{threshold}'    # Clean threshold (e.g., '0.1mJy')
deconvolver  = '{deconvolver}'  # 'hogbom', 'clark', 'multiscale', 'mtmfs'
specmode     = '{specmode}'     # 'mfs' or 'cube'

# ── Pre-imaging checks ────────────────────────────────────────
print(f"[QUASAR] Starting imaging for {{target}}")
os.makedirs(imagename.split('/')[0], exist_ok=True)

# ── Flagging ─────────────────────────────────────────────────
flagdata(vis=vis, mode='tfcrop', correlation='ABS_ALL',
         ntime='scan', combinescans=False, extendflags=False,
         flagbackup=True)

# ── Run tclean ───────────────────────────────────────────────
tclean(
    vis=vis,
    imagename=imagename,
    field=target,
    spw='',
    cell=cell,
    imsize=imsize,
    specmode=specmode,
    deconvolver=deconvolver,
    weighting=weighting,
    robust=robust,
    niter=niter,
    threshold=threshold,
    interactive=False,
    savemodel='modelcolumn',
    pbcor=True,
)

# ── Export to FITS ────────────────────────────────────────────
for suffix in ['.image', '.image.pbcor', '.residual', '.model', '.psf']:
    img = imagename + suffix
    if os.path.exists(img):
        exportfits(imagename=img, fitsimage=img + '.fits', overwrite=True)
        print(f"[QUASAR] Exported: {{img}}.fits")

print("[QUASAR] Imaging complete!")
"""

CALIBRATION_TEMPLATE = """
# ============================================================
# CASA Calibration Script — Generated by Quasar AI
# Target: {target} | Flux Cal: {flux_cal} | Phase Cal: {phase_cal}
# ============================================================

vis              = '{vis}'
flux_calibrator  = '{flux_cal}'
phase_calibrator = '{phase_cal}'
target           = '{target}'
refant           = '{refant}'       # Reference antenna (e.g., 'DA41')
spw              = '{spw}'          # Spectral window (e.g., '0,1,2,3')

print("[QUASAR] Starting ALMA pipeline calibration")

# ── Flagging autocorrelations ─────────────────────────────────
flagdata(vis=vis, mode='manual', autocorr=True)
flagdata(vis=vis, mode='shadow')
flagdata(vis=vis, mode='tfcrop', flagbackup=True)

# ── Set flux model for calibrator ────────────────────────────
setjy(vis=vis, field=flux_calibrator, standard='Butler-JPL-Horizons 2012')

# ── Delay calibration ─────────────────────────────────────────
gaincal(
    vis=vis, caltable='delay.cal', field=flux_calibrator,
    refant=refant, gaintype='K', solint='inf'
)

# ── Bandpass calibration ─────────────────────────────────────
bandpass(
    vis=vis, caltable='bandpass.cal', field=flux_calibrator,
    refant=refant, solint='inf', gaintable=['delay.cal']
)

# ── Phase calibration ─────────────────────────────────────────
gaincal(
    vis=vis, caltable='phase.cal', field=phase_calibrator,
    refant=refant, gaintype='G', solint='int', calmode='p',
    gaintable=['delay.cal', 'bandpass.cal']
)

# ── Amplitude calibration ─────────────────────────────────────
gaincal(
    vis=vis, caltable='amp.cal', field=phase_calibrator,
    refant=refant, gaintype='G', solint='inf', calmode='a',
    gaintable=['delay.cal', 'bandpass.cal', 'phase.cal']
)

# ── Flux scaling ──────────────────────────────────────────────
fluxscale(
    vis=vis, caltable='amp.cal', fluxtable='flux.cal',
    reference=flux_calibrator
)

# ── Apply calibrations to target ─────────────────────────────
applycal(
    vis=vis, field=target, calwt=False,
    gaintable=['delay.cal', 'bandpass.cal', 'phase.cal', 'flux.cal']
)

# ── Split calibrated target data ─────────────────────────────
split(vis=vis, outputvis='{target}_calibrated.ms', field=target, datacolumn='corrected')

print("[QUASAR] Calibration complete! Output: {target}_calibrated.ms")
"""


class CASAScriptGenerator:
    """Generate CASA data reduction scripts from observation parameters."""

    def generate_casa_imaging_script(
        self,
        target: str,
        vis: str,
        band: str = "6",
        cell: str = "0.02arcsec",
        imsize: int = 1024,
        weighting: str = "briggs",
        robust: float = 0.5,
        niter: int = 10000,
        threshold: str = "0.1mJy",
        specmode: str = "mfs",
        deconvolver: str = "hogbom",
        imagename: Optional[str] = None,
        config: str = "C-5",
    ) -> Dict[str, Any]:
        """
        Generate a CASA tclean imaging script.

        Args:
            target: Target source name (used in field selection)
            vis: Path to the calibrated Measurement Set (.ms file)
            band: ALMA band number (string, e.g. '6')
            cell: Cell size (e.g. '0.02arcsec')
            imsize: Square image size in pixels
            weighting: Visibility weighting ('briggs', 'natural', 'uniform')
            robust: Briggs robust parameter (-2 to +2, 0.5 = default)
            niter: Maximum clean iterations
            threshold: Clean stopping threshold (e.g. '0.1mJy')
            specmode: 'mfs' for continuum, 'cube' for line
            deconvolver: 'hogbom', 'clark', 'multiscale', or 'mtmfs'
            imagename: Output image name (auto-derived if None)
            config: ALMA array configuration (for documentation)

        Returns:
            dict with 'script' containing the CASA Python code
        """
        try:
            img_name = imagename or f"images/{target.replace(' ', '_')}_Band{band}"
            script = IMAGING_TEMPLATE.format(
                target=target,
                vis=vis,
                band=band,
                config=config,
                cell=cell,
                imsize=[imsize, imsize],
                weighting=weighting,
                robust=robust,
                niter=niter,
                threshold=threshold,
                specmode=specmode,
                deconvolver=deconvolver,
                imagename=img_name,
            )

            return {
                "success": True,
                "script_type": "casa_imaging",
                "target": target,
                "band": band,
                "script": script,
                "usage": "Save this as `imaging.py` and run in CASA: `execfile('imaging.py')`",
                "notes": [
                    f"Cell size {cell} should be ~1/5 of your synthesized beam.",
                    f"Imsize {imsize}px should be at least 3x your primary beam FWHM.",
                    f"Threshold {threshold} is ~3-5σ of expected RMS noise.",
                    "Run `listobs(vis=vis)` first to confirm field names and SPW IDs.",
                ]
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    def generate_casa_calibration_script(
        self,
        target: str,
        vis: str,
        flux_cal: str,
        phase_cal: str,
        refant: str,
        spw: str = "",
    ) -> Dict[str, Any]:
        """
        Generate a CASA manual calibration script.

        Args:
            target: Science target name
            vis: Input Measurement Set path
            flux_cal: Flux calibrator field name (e.g., 'J1517-2422')
            phase_cal: Phase calibrator field name
            refant: Reference antenna name (e.g., 'DA41')
            spw: Spectral window selection (empty = all)

        Returns:
            dict with 'script' containing the CASA calibration code
        """
        try:
            script = CALIBRATION_TEMPLATE.format(
                target=target,
                vis=vis,
                flux_cal=flux_cal,
                phase_cal=phase_cal,
                refant=refant,
                spw=spw or "",
            ).replace("{target}_calibrated", f"{target.replace(' ', '_')}_calibrated")

            return {
                "success": True,
                "script_type": "casa_calibration",
                "target": target,
                "flux_calibrator": flux_cal,
                "phase_calibrator": phase_cal,
                "script": script,
                "usage": "Save as `calibrate.py` and run in CASA: `execfile('calibrate.py')`",
                "notes": [
                    "Run `listobs` first to find the correct field names.",
                    f"Verify reference antenna `{refant}` is not on the fringe of the array.",
                    "Check calibration tables with `plotcal` before applying.",
                    "For ALMA pipeline data, prefer the ALMA Quality Assurance pipeline instead.",
                ]
            }
        except Exception as e:
            return {"success": False, "error": str(e)}
