"""
Code Generation Service for Radio Astronomy Data Analysis
Generates Python code templates for common radio astronomy tasks
"""

from typing import Dict, List, Optional, Any
import pandas as pd

class RadioCodeGenerator:
    """Generate Python code for radio astronomy data analysis"""
    
    @staticmethod
    def generate_data_loading_code(data_info: Dict[str, Any]) -> str:
        """Generate code for loading radio astronomy data"""
        columns = data_info.get('columns', [])
        num_obs = data_info.get('num_observations', 0)
        
        code = f'''"""
Radio Astronomy Data Analysis Script
Generated by Quasar AI Assistant
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.time import Time
import warnings
warnings.filterwarnings('ignore')

# Load the observation data
def load_observations(file_path):
    """Load radio astronomy observations from CSV/FITS file"""
    try:
        # For CSV files
        if file_path.endswith('.csv'):
            df = pd.read_csv(file_path)
        # For FITS tables
        elif file_path.endswith('.fits'):
            from astropy.table import Table
            table = Table.read(file_path)
            df = table.to_pandas()
        else:
            raise ValueError("Unsupported file format")
        
        print(f"Loaded {{len(df)}} observations")
        print(f"Columns: {{list(df.columns)}}")
        return df
    except Exception as e:
        print(f"Error loading data: {{e}}")
        return None

# Example usage
# df = load_observations('your_data.csv')
'''
        return code
    
    @staticmethod
    def generate_statistical_analysis_code(columns: List[str]) -> str:
        """Generate code for statistical analysis"""
        
        code = '''
# Statistical Analysis
def analyze_observations(df):
    """Perform statistical analysis on observation data"""
    
    print("=" * 50)
    print("STATISTICAL SUMMARY")
    print("=" * 50)
    
    # Basic statistics
    print("\\nDataset Overview:")
    print(f"Total observations: {len(df)}")
    '''
        
        if 'facility_name' in columns:
            code += '''
    # Facility distribution
    if 'facility_name' in df.columns:
        print("\\nObservations by Facility:")
        facility_counts = df['facility_name'].value_counts()
        for facility, count in facility_counts.items():
            print(f"  {facility}: {count} ({count/len(df)*100:.1f}%)")
    '''
        
        if 'freq_min_ghz' in columns and 'freq_max_ghz' in columns:
            code += '''
    # Frequency coverage
    if 'freq_min_ghz' in df.columns and 'freq_max_ghz' in df.columns:
        print("\\nFrequency Coverage:")
        print(f"  Min frequency: {df['freq_min_ghz'].min():.2f} GHz")
        print(f"  Max frequency: {df['freq_max_ghz'].max():.2f} GHz")
        print(f"  Mean frequency: {df['freq_min_ghz'].mean():.2f} GHz")
        
        # Identify bands
        def identify_band(freq_ghz):
            if freq_ghz < 0.5:
                return 'P-band'
            elif freq_ghz < 2:
                return 'L-band'
            elif freq_ghz < 4:
                return 'S-band'
            elif freq_ghz < 8:
                return 'C-band'
            elif freq_ghz < 12:
                return 'X-band'
            elif freq_ghz < 18:
                return 'Ku-band'
            elif freq_ghz < 27:
                return 'K-band'
            elif freq_ghz < 40:
                return 'Ka-band'
            else:
                return 'mm/sub-mm'
        
        df['band'] = df['freq_min_ghz'].apply(identify_band)
        print("\\nObservations by Band:")
        band_counts = df['band'].value_counts()
        for band, count in band_counts.items():
            print(f"  {band}: {count}")
    '''
        
        if 'duration_hours' in columns:
            code += '''
    # Observation duration statistics
    if 'duration_hours' in df.columns:
        print("\\nObservation Duration:")
        print(f"  Total time: {df['duration_hours'].sum():.1f} hours")
        print(f"  Mean duration: {df['duration_hours'].mean():.2f} hours")
        print(f"  Median duration: {df['duration_hours'].median():.2f} hours")
        print(f"  Max duration: {df['duration_hours'].max():.2f} hours")
    '''
        
        if 'target_name' in columns:
            code += '''
    # Top targets
    if 'target_name' in df.columns:
        print("\\nTop 10 Most Observed Targets:")
        top_targets = df['target_name'].value_counts().head(10)
        for target, count in top_targets.items():
            print(f"  {target}: {count} observations")
    '''
        
        code += '''
    return df

# Run analysis
# analyze_observations(df)
'''
        return code
    
    @staticmethod
    def generate_visualization_code(columns: List[str]) -> str:
        """Generate visualization code"""
        
        code = '''
# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")

def create_visualizations(df):
    """Create comprehensive visualizations of the data"""
    
    fig = plt.figure(figsize=(16, 12))
    '''
        
        plot_num = 1
        total_plots = 0
        
        # Count how many plots we'll make
        if 'obs_date' in columns:
            total_plots += 1
        if 'freq_min_ghz' in columns:
            total_plots += 1
        if 's_ra' in columns and 's_dec' in columns:
            total_plots += 1
        if 'duration_hours' in columns:
            total_plots += 1
        
        rows = (total_plots + 1) // 2
        cols = 2 if total_plots > 1 else 1
        
        if 'obs_date' in columns:
            code += f'''
    # Timeline of observations
    ax{plot_num} = plt.subplot({rows}, {cols}, {plot_num})
    if 'obs_date' in df.columns:
        df['obs_date'] = pd.to_datetime(df['obs_date'])
        df_sorted = df.sort_values('obs_date')
        
        # Group by month
        monthly = df_sorted.groupby(df_sorted['obs_date'].dt.to_period('M')).size()
        monthly.plot(kind='bar', ax=ax{plot_num}, color='steelblue')
        ax{plot_num}.set_title('Observations Timeline', fontsize=14, fontweight='bold')
        ax{plot_num}.set_xlabel('Month')
        ax{plot_num}.set_ylabel('Number of Observations')
        ax{plot_num}.tick_params(axis='x', rotation=45)
    '''
            plot_num += 1
        
        if 'freq_min_ghz' in columns:
            code += f'''
    # Frequency distribution
    ax{plot_num} = plt.subplot({rows}, {cols}, {plot_num})
    if 'freq_min_ghz' in df.columns:
        freq_data = df['freq_min_ghz'].dropna()
        ax{plot_num}.hist(freq_data, bins=30, color='purple', alpha=0.7, edgecolor='black')
        ax{plot_num}.set_title('Frequency Distribution', fontsize=14, fontweight='bold')
        ax{plot_num}.set_xlabel('Frequency (GHz)')
        ax{plot_num}.set_ylabel('Count')
        ax{plot_num}.set_yscale('log')
    '''
            plot_num += 1
        
        if 's_ra' in columns and 's_dec' in columns:
            code += f'''
    # Sky coverage plot
    ax{plot_num} = plt.subplot({rows}, {cols}, {plot_num}, projection='mollweide')
    if 's_ra' in df.columns and 's_dec' in df.columns:
        # Convert to radians for mollweide projection
        ra_rad = np.deg2rad(df['s_ra'] - 180)  # Center at RA=180
        dec_rad = np.deg2rad(df['s_dec'])
        
        ax{plot_num}.scatter(ra_rad, dec_rad, c='gold', s=10, alpha=0.6)
        ax{plot_num}.grid(True, alpha=0.3)
        ax{plot_num}.set_title('Sky Coverage (Mollweide Projection)', fontsize=14, fontweight='bold')
        ax{plot_num}.set_xlabel('RA')
        ax{plot_num}.set_ylabel('Dec')
    '''
            plot_num += 1
        
        if 'duration_hours' in columns:
            code += f'''
    # Duration distribution
    ax{plot_num} = plt.subplot({rows}, {cols}, {plot_num})
    if 'duration_hours' in df.columns:
        duration_data = df['duration_hours'].dropna()
        ax{plot_num}.boxplot([duration_data], vert=False)
        ax{plot_num}.set_title('Observation Duration Distribution', fontsize=14, fontweight='bold')
        ax{plot_num}.set_xlabel('Duration (hours)')
        ax{plot_num}.set_yticklabels(['All Observations'])
    '''
            plot_num += 1
        
        code += '''
    plt.tight_layout()
    plt.savefig('radio_observations_analysis.png', dpi=300, bbox_inches='tight')
    plt.show()
    
    return fig

# Create visualizations
# fig = create_visualizations(df)
'''
        return code
    
    @staticmethod
    def generate_frequency_analysis_code() -> str:
        """Generate code for frequency/spectral analysis"""
        
        code = '''
# Frequency and Spectral Analysis
def analyze_spectrum(df):
    """Analyze frequency/spectral properties"""
    
    # Calculate spectral indices if multiple frequencies available
    def calculate_spectral_index(freq1, flux1, freq2, flux2):
        """Calculate spectral index: S ∝ ν^α"""
        alpha = np.log(flux2/flux1) / np.log(freq2/freq1)
        return alpha
    
    # Identify RFI-affected frequencies
    def identify_rfi_bands():
        """Common RFI frequencies to avoid"""
        rfi_bands = {
            'GPS L1': (1.565, 1.585),  # GHz
            'GPS L2': (1.217, 1.237),
            'GPS L5': (1.164, 1.189),
            'Iridium': (1.616, 1.626),
            'GLONASS': (1.593, 1.610),
            'Galileo E1': (1.559, 1.591),
            'Cell phones': (0.824, 0.960),
            'WiFi 2.4GHz': (2.400, 2.484),
            'WiFi 5GHz': (5.150, 5.850)
        }
        return rfi_bands
    
    # Check for RFI contamination
    rfi_bands = identify_rfi_bands()
    
    if 'freq_min_ghz' in df.columns and 'freq_max_ghz' in df.columns:
        print("\\nChecking for potential RFI contamination...")
        
        affected_obs = []
        for idx, row in df.iterrows():
            freq_min = row['freq_min_ghz']
            freq_max = row['freq_max_ghz']
            
            for rfi_name, (rfi_min, rfi_max) in rfi_bands.items():
                if not (freq_max < rfi_min or freq_min > rfi_max):
                    affected_obs.append((idx, rfi_name))
                    break
        
        if affected_obs:
            print(f"  Warning: {len(affected_obs)} observations may be affected by RFI")
            print("  Common RFI sources detected:")
            rfi_sources = {}
            for _, source in affected_obs:
                rfi_sources[source] = rfi_sources.get(source, 0) + 1
            for source, count in sorted(rfi_sources.items(), key=lambda x: x[1], reverse=True):
                print(f"    {source}: {count} observations")
        else:
            print("  No obvious RFI contamination detected")
    
    # Bandwidth and resolution analysis
    if 'bandwidth_mhz' in df.columns:
        print("\\nBandwidth Statistics:")
        print(f"  Mean bandwidth: {df['bandwidth_mhz'].mean():.1f} MHz")
        print(f"  Max bandwidth: {df['bandwidth_mhz'].max():.1f} MHz")
        
        # Calculate velocity resolution for spectral line observations
        if 'freq_min_ghz' in df.columns:
            c = 299792.458  # km/s
            mean_freq = df['freq_min_ghz'].mean() * 1000  # Convert to MHz
            velocity_res = c * (df['bandwidth_mhz'] / df['num_channels']) / mean_freq
            print(f"  Typical velocity resolution: {velocity_res.mean():.2f} km/s")
    
    return df

# Perform frequency analysis
# analyze_spectrum(df)
'''
        return code
    
    @staticmethod
    def generate_coordinate_analysis_code() -> str:
        """Generate code for coordinate and position analysis"""
        
        code = '''
# Coordinate and Position Analysis
from astropy.coordinates import SkyCoord, FK5
from astropy import units as u

def analyze_positions(df):
    """Analyze spatial distribution and coordinates"""
    
    if 's_ra' not in df.columns or 's_dec' not in df.columns:
        print("No coordinate information available")
        return
    
    # Create SkyCoord objects
    coords = SkyCoord(ra=df['s_ra'].values*u.degree, 
                      dec=df['s_dec'].values*u.degree, 
                      frame='icrs')
    
    # Convert to Galactic coordinates
    gal_coords = coords.galactic
    df['gal_l'] = gal_coords.l.degree
    df['gal_b'] = gal_coords.b.degree
    
    print("\\nSpatial Distribution Analysis:")
    print(f"  RA range: {df['s_ra'].min():.2f}° to {df['s_ra'].max():.2f}°")
    print(f"  Dec range: {df['s_dec'].min():.2f}° to {df['s_dec'].max():.2f}°")
    print(f"  Galactic longitude range: {df['gal_l'].min():.2f}° to {df['gal_l'].max():.2f}°")
    print(f"  Galactic latitude range: {df['gal_b'].min():.2f}° to {df['gal_b'].max():.2f}°")
    
    # Identify observations near Galactic plane
    near_plane = df[np.abs(df['gal_b']) < 10]
    print(f"\\nObservations near Galactic plane (|b| < 10°): {len(near_plane)}")
    
    # Identify extragalactic observations (high galactic latitude)
    extragalactic = df[np.abs(df['gal_b']) > 30]
    print(f"Likely extragalactic observations (|b| > 30°): {len(extragalactic)}")
    
    # Calculate angular separations between observations
    if len(df) > 1:
        separations = []
        for i in range(len(coords)-1):
            sep = coords[i].separation(coords[i+1])
            separations.append(sep.degree)
        
        print(f"\\nAngular separations between consecutive observations:")
        print(f"  Mean: {np.mean(separations):.2f}°")
        print(f"  Median: {np.median(separations):.2f}°")
        print(f"  Max: {np.max(separations):.2f}°")
    
    # Create sky density map
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))
    
    # RA-Dec plot
    ax1.scatter(df['s_ra'], df['s_dec'], alpha=0.5, s=20)
    ax1.set_xlabel('RA (degrees)')
    ax1.set_ylabel('Dec (degrees)')
    ax1.set_title('Sky Distribution (Equatorial)')
    ax1.grid(True, alpha=0.3)
    
    # Galactic coordinates plot
    ax2.scatter(df['gal_l'], df['gal_b'], alpha=0.5, s=20, c='orange')
    ax2.set_xlabel('Galactic Longitude (degrees)')
    ax2.set_ylabel('Galactic Latitude (degrees)')
    ax2.set_title('Sky Distribution (Galactic)')
    ax2.axhline(y=0, color='gray', linestyle='--', alpha=0.5, label='Galactic Plane')
    ax2.grid(True, alpha=0.3)
    ax2.legend()
    
    plt.tight_layout()
    plt.savefig('sky_distribution.png', dpi=300, bbox_inches='tight')
    plt.show()
    
    return df

# Analyze positions
# df = analyze_positions(df)
'''
        return code
    
    @staticmethod
    def generate_complete_analysis_script(data: pd.DataFrame) -> str:
        """Generate a complete analysis script based on the data"""
        
        columns = list(data.columns) if isinstance(data, pd.DataFrame) else []
        data_info = {
            'columns': columns,
            'num_observations': len(data) if isinstance(data, pd.DataFrame) else 0
        }
        
        # Combine all code sections
        script = RadioCodeGenerator.generate_data_loading_code(data_info)
        script += "\n" + RadioCodeGenerator.generate_statistical_analysis_code(columns)
        script += "\n" + RadioCodeGenerator.generate_visualization_code(columns)
        script += "\n" + RadioCodeGenerator.generate_frequency_analysis_code()
        script += "\n" + RadioCodeGenerator.generate_coordinate_analysis_code()
        
        # Add main execution block
        script += '''

# Main execution
if __name__ == "__main__":
    # Load your data
    file_path = "your_observations.csv"  # Update with your file path
    df = load_observations(file_path)
    
    if df is not None:
        # Run all analyses
        print("\\n" + "="*60)
        print("RADIO ASTRONOMY DATA ANALYSIS")
        print("="*60)
        
        # Statistical analysis
        df = analyze_observations(df)
        
        # Frequency analysis
        df = analyze_spectrum(df)
        
        # Position analysis
        df = analyze_positions(df)
        
        # Create visualizations
        fig = create_visualizations(df)
        
        # Save processed data
        output_file = "processed_observations.csv"
        df.to_csv(output_file, index=False)
        print(f"\\nProcessed data saved to {output_file}")
        
        print("\\nAnalysis complete!")
'''
        
        return script
