import json
import uuid

class NotebookGenerator:
    """Service to generate Jupyter Notebooks (.ipynb) dynamically."""
    
    def __init__(self):
        self.notebook = {
            "cells": [],
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "codemirror_mode": {
                        "name": "ipython",
                        "version": 3
                    },
                    "file_extension": ".py",
                    "mimetype": "text/x-python",
                    "name": "python",
                    "nbconvert_exporter": "python",
                    "pygments_lexer": "ipython3",
                    "version": "3.8.0"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 4
        }
    
    def _create_cell(self, cell_type: str, source: str) -> dict:
        """Helper to create a notebook cell."""
        # Ensure source ends with newline if required by format, or just split into lists
        source_lines = [line + '\n' for line in source.split('\n')]
        # remove the last newline from the last line
        if source_lines:
            source_lines[-1] = source_lines[-1].rstrip('\n')
            
        cell = {
            "cell_type": cell_type,
            "metadata": {},
            "source": source_lines
        }
        if cell_type == "code":
            cell["execution_count"] = None
            cell["outputs"] = []
        return cell

    def add_markdown_cell(self, text: str):
        """Add a markdown cell."""
        self.notebook["cells"].append(self._create_cell("markdown", text))

    def add_code_cell(self, code: str):
        """Add a Python code cell."""
        self.notebook["cells"].append(self._create_cell("code", code))

    def generate_json(self) -> str:
        """Return the notebook as a JSON string."""
        return json.dumps(self.notebook, indent=2)

    def generate_dict(self) -> dict:
        """Return the notebook as a dictionary."""
        return self.notebook

def generate_analysis_notebook(title: str, steps: list) -> dict:
    """
    Generate an analysis notebook from a list of steps.
    Each step should be a dict: {'type': 'markdown' | 'code', 'content': '...'}
    """
    nb = NotebookGenerator()
    nb.add_markdown_cell(f"# {title}\nAuto-generated QUASAR Analysis Notebook.")
    nb.add_code_cell("import numpy as np\nimport matplotlib.pyplot as plt\nfrom astropy.io import fits\nfrom spectral_cube import SpectralCube\nimport astropy.units as u")
    
    for step in steps:
        if step.get("type") == "markdown":
            nb.add_markdown_cell(step.get("content", ""))
        elif step.get("type") == "code":
            nb.add_code_cell(step.get("content", ""))
            
    return nb.generate_dict()


def generate_conductor_notebook(
    query: str,
    subtasks: list,
    results: dict,
    dag_summary: dict = None,
) -> dict:
    """
    Generate a research-grade Jupyter notebook from a Conductor DAG execution.

    Builds a comprehensive, reproducible notebook containing:
    - The user's original query
    - Requirements / install cell
    - For each subtask: a markdown heading describing the step,
      plus a Python code cell showing how to reproduce it.
    - A summary section with the final synthesis.

    Parameters
    ----------
    query : str
        The user's original question.
    subtasks : list[dict]
        The DAG subtask definitions (id, description, agent_type, depends_on).
    results : dict
        Mapping of task_id → result from the Conductor execution.
    dag_summary : dict, optional
        Output of dag.get_execution_summary() for stats.

    Returns
    -------
    dict
        A Jupyter notebook dict (ready for JSON serialisation).
    """
    nb = NotebookGenerator()

    # ── Title cell ──
    nb.add_markdown_cell(
        f"# 🔭 Quasar Research Notebook\n\n"
        f"**Query:** {query}\n\n"
        f"*Auto-generated by the Quasar Multi-Agent Workforce.*\n\n"
        f"This notebook contains the code to reproduce each step of "
        f"the analysis that was performed."
    )

    # ── Requirements cell ──
    nb.add_code_cell(
        "# Install required packages (uncomment if needed)\n"
        "# !pip install astroquery pyvo astropy matplotlib spectral-cube numpy requests"
    )

    # ── Standard imports ──
    nb.add_code_cell(
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "from astropy.io import fits\n"
        "from astropy.coordinates import SkyCoord\n"
        "import astropy.units as u\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "\n"
        "# Optional: ALMA archive access\n"
        "try:\n"
        "    from astroquery.alma import Alma\n"
        "    from astroquery.simbad import Simbad\n"
        "except ImportError:\n"
        "    print('Install astroquery: pip install astroquery')\n"
        "\n"
        "# Optional: visualization\n"
        "try:\n"
        "    from astropy.visualization import ZScaleInterval, ImageNormalize, SqrtStretch\n"
        "except ImportError:\n"
        "    pass"
    )

    # ── Instructions ──
    nb.add_markdown_cell(
        "## 📋 Instructions\n\n"
        "1. Run each cell in order — they mirror the sub-tasks the agents executed.\n"
        "2. Some cells may require network access to the ALMA archive or NASA ADS.\n"
        "3. `access_url` values come from actual archive queries and should work directly.\n"
        "4. If a cell errors, check that the required packages are installed."
    )

    # ── One section per subtask ──
    for st in subtasks:
        tid = st.get("id", "?")
        desc = st.get("description", "Unnamed step")
        agent = st.get("agent_type", "general")
        result = results.get(tid)

        status_emoji = "✅" if result is not None else "❌"
        
        # Build agent findings text
        findings = ""
        if result:
            res_str = str(result)
            findings = f"**Agent Findings:**\n\n```text\n{res_str}\n```"
        else:
            findings = "⚠️ *Task failed to produce a result.*"

        nb.add_markdown_cell(
            f"## {status_emoji} Step {tid}: {desc}\n\n"
            f"*Agent type: `{agent}`*\n\n"
            f"{findings}"
        )

        # Build a code cell template for reproducibility
        code = _build_code_cell(agent, desc, result)
        if code:
            nb.add_code_cell(code)

    # ── Summary section ──
    if dag_summary:
        total = dag_summary.get("total_tasks", 0)
        ok = dag_summary.get("completed", 0)
        fail = dag_summary.get("failed", 0)
        nb.add_markdown_cell(
            f"## 📊 Execution Summary\n\n"
            f"| Metric | Value |\n"
            f"|--------|-------|\n"
            f"| Total tasks | {total} |\n"
            f"| Completed | {ok} |\n"
            f"| Failed | {fail} |"
        )

    nb.add_markdown_cell(
        "---\n\n"
        "*Notebook auto-generated by [Quasar](https://github.com/your-org/quasar). "
        "Feel free to modify and extend.*"
    )

    return nb.generate_dict()


def _build_code_cell(agent_type: str, description: str, result) -> str:
    """
    Build a runnable Python code cell template for a subtask based on its agent type
    and the actual result data.
    """
    desc_lower = description.lower()
    
    if agent_type == "archive" or "alma" in desc_lower or "cadc" in desc_lower or "search" in desc_lower:
        return (
            f"# Reproducing: {description}\n"
            "from astroquery.alma import Alma\n"
            "import pandas as pd\n\n"
            "# 1. Define the query parameters based on the task\n"
            "# rs = Alma.query_object('TARGET_NAME') \n"
            "# df = rs.to_pandas()\n"
            "# df.head()"
        )

    if agent_type == "literature" or "paper" in desc_lower or "ads" in desc_lower:
         return (
            f"# Reproducing: {description}\n"
            "import requests\n"
            "import urllib.parse\n\n"
            "# Query the NASA ADS API (requires ADS_DEV_KEY token)\n"
            "# q = urllib.parse.quote('QUERY')\n"
            "# url = f'https://api.adsabs.harvard.edu/v1/search/query?q={{q}}&fl=title,author,bibcode'\n"
            "# print(f'Searching ADS: {{url}}')"
         )
         
    if agent_type == "viz" or "overlay" in desc_lower or "plot" in desc_lower or "render" in desc_lower:
         return (
             f"# Reproducing: {description}\n"
             "import matplotlib.pyplot as plt\n"
             "from astropy.io import fits\n"
             "from astropy.visualization import astropy_mpl_style\n"
             "plt.style.use(astropy_mpl_style)\n\n"
             "# 1. Load the FITS file from the archive\n"
             "# hdul = fits.open('FITS_URL_OR_PATH')\n"
             "# data = hdul[0].data\n\n"
             "# 2. Plot the image\n"
             "# plt.figure(figsize=(8,8))\n"
             "# plt.imshow(data, cmap='inferno', origin='lower')\n"
             "# plt.colorbar()\n"
             "# plt.show()"
         )
         
    if agent_type == "analysis" or "splatalogue" in desc_lower or "line" in desc_lower:
         return (
             f"# Reproducing: {description}\n"
             "from astroquery.splatalogue import Splatalogue\n"
             "import astropy.units as u\n\n"
             "# Query Splatalogue for molecular lines\n"
             "# lines = Splatalogue.query_lines(\n"
             "#     100 * u.GHz, \n"
             "#     115 * u.GHz, \n"
             "#     chemical_name=' CO ',\n"
             "#     energy_max=500,\n"
             "#     energy_type='eu_k'\n"
             "# )\n"
             "# lines.to_pandas().head()"
         )

    return (
        f"# Reproducing: {description}\n"
        f"# Agent type: {agent_type}\n"
        "# Custom code block for analytical script / synthesis."
    )
