import json
import uuid

class NotebookGenerator:
    """Service to generate Jupyter Notebooks (.ipynb) dynamically."""
    
    def __init__(self):
        self.notebook = {
            "cells": [],
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "codemirror_mode": {
                        "name": "ipython",
                        "version": 3
                    },
                    "file_extension": ".py",
                    "mimetype": "text/x-python",
                    "name": "python",
                    "nbconvert_exporter": "python",
                    "pygments_lexer": "ipython3",
                    "version": "3.8.0"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 4
        }
    
    def _create_cell(self, cell_type: str, source: str) -> dict:
        """Helper to create a notebook cell."""
        # Ensure source ends with newline if required by format, or just split into lists
        source_lines = [line + '\n' for line in source.split('\n')]
        # remove the last newline from the last line
        if source_lines:
            source_lines[-1] = source_lines[-1].rstrip('\n')
            
        cell = {
            "cell_type": cell_type,
            "metadata": {},
            "source": source_lines
        }
        if cell_type == "code":
            cell["execution_count"] = None
            cell["outputs"] = []
        return cell

    def add_markdown_cell(self, text: str):
        """Add a markdown cell."""
        self.notebook["cells"].append(self._create_cell("markdown", text))

    def add_code_cell(self, code: str):
        """Add a Python code cell."""
        self.notebook["cells"].append(self._create_cell("code", code))

    def generate_json(self) -> str:
        """Return the notebook as a JSON string."""
        return json.dumps(self.notebook, indent=2)

    def generate_dict(self) -> dict:
        """Return the notebook as a dictionary."""
        return self.notebook

def generate_analysis_notebook(title: str, steps: list) -> dict:
    """
    Generate an analysis notebook from a list of steps.
    Each step should be a dict: {'type': 'markdown' | 'code', 'content': '...'}
    """
    nb = NotebookGenerator()
    nb.add_markdown_cell(f"# {title}\nAuto-generated QUASAR Analysis Notebook.")
    nb.add_code_cell("import numpy as np\nimport matplotlib.pyplot as plt\nfrom astropy.io import fits\nfrom spectral_cube import SpectralCube\nimport astropy.units as u")
    
    for step in steps:
        if step.get("type") == "markdown":
            nb.add_markdown_cell(step.get("content", ""))
        elif step.get("type") == "code":
            nb.add_code_cell(step.get("content", ""))
            
    return nb.generate_dict()


def generate_conductor_notebook(
    query: str,
    subtasks: list,
    results: dict,
    dag_summary: dict = None,
) -> dict:
    """
    Generate a research-grade Jupyter notebook from a Conductor DAG execution.

    Builds a comprehensive, reproducible notebook containing:
    - The user's original query
    - Requirements / install cell
    - For each subtask: a markdown heading describing the step,
      plus a Python code cell showing how to reproduce it.
    - A summary section with the final synthesis.

    Parameters
    ----------
    query : str
        The user's original question.
    subtasks : list[dict]
        The DAG subtask definitions (id, description, agent_type, depends_on).
    results : dict
        Mapping of task_id → result from the Conductor execution.
    dag_summary : dict, optional
        Output of dag.get_execution_summary() for stats.

    Returns
    -------
    dict
        A Jupyter notebook dict (ready for JSON serialisation).
    """
    nb = NotebookGenerator()

    # ── Title cell ──
    nb.add_markdown_cell(
        f"# 🔭 Quasar Research Notebook\n\n"
        f"**Query:** {query}\n\n"
        f"*Auto-generated by the Quasar Multi-Agent Workforce.*\n\n"
        f"This notebook contains the code to reproduce each step of "
        f"the analysis that was performed."
    )

    # ── Requirements cell ──
    nb.add_code_cell(
        "# Install required packages (uncomment if needed)\n"
        "# !pip install astroquery pyvo astropy matplotlib spectral-cube numpy requests"
    )

    # ── Standard imports ──
    nb.add_code_cell(
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "from astropy.io import fits\n"
        "from astropy.coordinates import SkyCoord\n"
        "import astropy.units as u\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "\n"
        "# Optional: ALMA archive access\n"
        "try:\n"
        "    from astroquery.alma import Alma\n"
        "    from astroquery.simbad import Simbad\n"
        "except ImportError:\n"
        "    print('Install astroquery: pip install astroquery')\n"
        "\n"
        "# Optional: visualization\n"
        "try:\n"
        "    from astropy.visualization import ZScaleInterval, ImageNormalize, SqrtStretch\n"
        "except ImportError:\n"
        "    pass"
    )

    # ── Instructions ──
    nb.add_markdown_cell(
        "## 📋 Instructions\n\n"
        "1. Run each cell in order — they mirror the sub-tasks the agents executed.\n"
        "2. Some cells may require network access to the ALMA archive or NASA ADS.\n"
        "3. `access_url` values come from actual archive queries and should work directly.\n"
        "4. If a cell errors, check that the required packages are installed."
    )

    # ── One section per subtask ──
    for st in subtasks:
        tid = st.get("id", "?")
        desc = st.get("description", "Unnamed step")
        agent = st.get("agent_type", "general")
        result = results.get(tid)

        # Markdown heading for this subtask
        status_emoji = "✅" if result is not None else "❌"
        nb.add_markdown_cell(
            f"## {status_emoji} Step {tid}: {desc}\n\n"
            f"*Agent type: `{agent}`*"
        )

        # Build a code cell based on the agent type and result content.
        # We try to emit real, runnable code rather than just pasting results.
        code = _build_code_cell(agent, desc, result)
        nb.add_code_cell(code)

    # ── Summary section ──
    if dag_summary:
        total = dag_summary.get("total_tasks", 0)
        ok = dag_summary.get("completed", 0)
        fail = dag_summary.get("failed", 0)
        nb.add_markdown_cell(
            f"## 📊 Execution Summary\n\n"
            f"| Metric | Value |\n"
            f"|--------|-------|\n"
            f"| Total tasks | {total} |\n"
            f"| Completed | {ok} |\n"
            f"| Failed | {fail} |"
        )

    nb.add_markdown_cell(
        "---\n\n"
        "*Notebook auto-generated by [Quasar](https://github.com/your-org/quasar). "
        "Feel free to modify and extend.*"
    )

    return nb.generate_dict()


def _build_code_cell(agent_type: str, description: str, result) -> str:
    """
    Build a runnable Python code cell for a subtask based on its agent type
    and the actual result data.  Falls back to a commented result dump.
    """
    # Extract useful data from result
    if isinstance(result, dict):
        # Archive searches often return MOUS UIDs, access URLs, etc.
        mous_uids = result.get("top_mous_uids", [])
        access_urls = result.get("top_access_urls", [])
        total = result.get("total_results", "")

        if agent_type == "archive" and (mous_uids or access_urls):
            lines = [f"# {description}", ""]
            if "alma" in description.lower() or "search" in description.lower():
                # Emit a real astroquery search
                # Try to extract target name from description
                lines.append("from astroquery.alma import Alma")
                lines.append("alma = Alma()")
                lines.append(f"# Query returned {total} results")
                if mous_uids:
                    lines.append(f"mous_uids = {mous_uids!r}")
                    lines.append("")
                    lines.append("# List files for first MOUS UID")
                    lines.append("info = alma.get_data_info(mous_uids[0])")
                    lines.append("print(f'Found {len(info)} files')")
                    lines.append("info")
                elif access_urls:
                    lines.append(f"access_urls = {access_urls[:3]!r}")
            return "\n".join(lines)

        if agent_type == "viz" and result.get("type") == "image":
            url = result.get("image_url", "")
            return (
                f"# {description}\n"
                f"from IPython.display import Image, display\n"
                f"display(Image(url='{url}', width=600))"
            )

        if agent_type == "literature":
            result_str = json.dumps(result, default=str, indent=2)[:3000]
            return (
                f"# {description}\n"
                f"# Literature search results:\n"
                f"results = {result_str}\n"
                f"print(json.dumps(results, indent=2))"
            )

    # Fallback: dump the result as a comment
    result_str = str(result)[:2000] if result else "No result"
    return (
        f"# {description}\n"
        f"# Agent type: {agent_type}\n"
        f"#\n"
        f"# Result:\n"
        + "\n".join(f"# {line}" for line in result_str.split("\n")[:30])
    )
