"""GENERATED by scripts/gen_alma_kernel.py from tests/fixtures/alma_obscore_columns_2025-12.txt — do not edit by hand.

The always-on ALMA guardrail kernel injected into the system prompt
(core/prompts.ALMA_TAP_SCHEMA). Regenerate with
``python scripts/gen_alma_kernel.py``; tests assert it is current and under
400 tokens.
"""

ALMA_KERNEL_SNAPSHOT = 'alma_obscore_columns_2025-12.txt'
ALMA_KERNEL_TOKEN_BUDGET = 400

ALMA_TAP_SCHEMA = "ALMA ARCHIVE GUARDRAILS (ivoa.obscore; column snapshot 2025-12):\n- Rows are coverage records (repeat per execution block asdm_uid, field, SPW), NOT observations: datasets = distinct member_ous_uid (MOUS), executions = COUNT(DISTINCT asdm_uid), projects = proposal_id; report all three.\n- Units: frequency GHz, bandwidth Hz; em_min/em_max METERS; t_min/t_max MJD; obs_release_date ISO; velocity_resolution m/s; spatial_resolution arcsec.\n- Coverage: em_min <= 0.29979/nu_lo AND em_max >= 0.29979/nu_hi, then check frequency_support SPW windows; frequency +/- bandwidth/2 is WRONG.\n- Cone: INTERSECTS(CIRCLE('ICRS',ra,dec,r), s_region) = 1 OR CONTAINS(POINT('ICRS',s_ra,s_dec), CIRCLE(...)) = 1 (s_ra/s_dec alone misses mosaics).\n- band_list is space-delimited ('5 10' = band-to-band): match tokens. Public: data_rights = 'Public'. Science rows: science_observation = 'T'.\n- qa2_passed T/F cannot give PASS/SEMIPASS/FAIL (get_alma_qa2_status). access_url = MOUS DataLink URL (list_alma_files), not a file. No calibrated MS is delivered: restore via scriptForPI under the package CASA version, or ARC/SRDP.\n- Resolve names to coordinates and cone-search (search_by_target does); never string-match PI target_name except moving/solar targets, and say so.\n- Mosaics, moving/solar, Total Power, polarization, band-to-band, VLBI, restore, TOPO vs LSRK, pipeline history: browse_alma_guidance(topic).\n"
