import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";
import * as React from "react";
import * as jsxRuntime from "react/jsx-runtime";
import { renderToStaticMarkup } from "react-dom/server";
import * as lucide from "lucide-react";
import * as hips from "../src/lib/hips-imagery.js";
import * as saveLib from "../src/lib/save-image.js";

function loadTs(file, dependencies = {}) {
    const source = fs.readFileSync(new URL(file, import.meta.url), "utf8");
    const { outputText } = ts.transpileModule(source, {
        compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, jsx: ts.JsxEmit.ReactJSX },
    });
    const module = { exports: {} };
    vm.runInNewContext(outputText, {
        module, exports: module.exports, URL, setTimeout,
        require: name => {
            if (!(name in dependencies)) throw new Error(`Unexpected import: ${name}`);
            return dependencies[name];
        },
    });
    return module.exports;
}

const stub = name => () => React.createElement("i", { "data-stub": name });
const { HipsImageCard } = loadTs("../src/components/HipsImageCard.tsx", {
    "react/jsx-runtime": jsxRuntime,
    react: React,
    "lucide-react": lucide,
    "./AladinSkyView": { AladinSkyView: stub("aladin"), SURVEYS: [{ id: "P/DSS2/color", label: "DSS" }] },
    "./BlinkCard": { BlinkCard: stub("blink") },
    "./ImageLightbox": { ImageLightbox: stub("lightbox") },
    "./QueryProvenance": { QueryProvenance: stub("provenance") },
    "./IllustrativeBadge": { IllustrativeBadge: stub("illustrative") },
    "../lib/hips-imagery": hips,
    "../lib/export-decision": { previewBadgeFacts: () => ({}) },
    "../lib/save-image": saveLib,
});

const render = props => renderToStaticMarkup(React.createElement(HipsImageCard, props));

test("a generated image renders the AI-generated card, not the data-figure card", () => {
    const markup = render({
        imageUrl: "http://localhost:8000/api/images/gen_abc.png",
        caption: "Generated by gpt-image-2",
        imageMeta: { kind: "generated", model: "gpt-image-2" },
    });
    assert.match(markup, /data-image-kind="generated"/);
    assert.match(markup, /AI-generated/);
    assert.match(markup, />gpt-image-2</);
    assert.match(markup, /Download/);
    assert.match(markup, /Full size/);
    assert.match(markup, /not an observation or real data/);
    assert.doesNotMatch(markup, /data-stub="illustrative"/, "no cite-the-source-table badge on artwork");
    assert.doesNotMatch(markup, /data-stub="provenance"/);
});

test("a plain rendered figure keeps the illustrative badge", () => {
    const markup = render({ imageUrl: "/plots/cmd.png", caption: "CMD" });
    assert.match(markup, /data-stub="illustrative"/);
    assert.doesNotMatch(markup, /AI-generated/);
});

function fakeEnv({ ok = true, throws = false } = {}) {
    const log = [];
    const anchor = { click: () => log.push(["click", anchor.href, anchor.download]), remove: () => log.push(["remove"]) };
    return {
        log,
        fetch: async url => {
            log.push(["fetch", url]);
            if (throws) throw new TypeError("Failed to fetch");
            return { ok, status: ok ? 200 : 404, blob: async () => ({ size: 3 }) };
        },
        URL: { createObjectURL: () => "blob:1", revokeObjectURL: u => log.push(["revoke", u]) },
        document: { createElement: () => anchor, body: { appendChild: () => log.push(["append"]) } },
        window: { open: (...args) => log.push(["open", ...args]) },
        setTimeout: fn => fn(),
    };
}

test("Download fetches the image as a blob and saves it under a model-named file", async () => {
    const env = fakeEnv();
    const outcome = await saveLib.saveImage("http://localhost:8000/api/images/gen_abc.jpg", "gemini-3.1-flash-image", env);
    assert.equal(outcome, "downloaded");
    const click = env.log.find(e => e[0] === "click");
    assert.equal(click[1], "blob:1");
    assert.match(click[2], /^quasar-gemini-3\.1-flash-image-\d+\.jpg$/);
    assert.ok(env.log.some(e => e[0] === "revoke"));
    assert.ok(!env.log.some(e => e[0] === "open"));
});

test("Download falls back to opening the image when the fetch fails or 404s", async () => {
    for (const opts of [{ throws: true }, { ok: false }]) {
        const env = fakeEnv(opts);
        assert.equal(await saveLib.saveImage("http://h/api/images/gen_x.png", "gpt-image-2", env), "opened");
        assert.deepEqual(env.log.find(e => e[0] === "open"), ["open", "http://h/api/images/gen_x.png", "_blank", "noopener,noreferrer"]);
        assert.ok(!env.log.some(e => e[0] === "click"));
    }
});

test("download names keep the image extension and default to png", () => {
    assert.equal(saveLib.downloadName("/api/images/gen_a.webp?x=1", "m", 5), "quasar-m-5.webp");
    assert.equal(saveLib.downloadName("data:image/png;base64,AAA", undefined, 5), "quasar-generated-5.png");
});
