#!/usr/bin/env python3
"""
gen_alma_kernel.py — generate the always-on ALMA guardrail kernel (INT-6).

The kernel replaces the old 770-token ``ALMA_TAP_SCHEMA`` table (which carried
four factual errors: bandwidth GHz, cont_sens_bandwidth, velocity km/s,
access_url = download URL) with a ~300-token block of the skill's
non-negotiables. It is GENERATED from a dated, checked-in ObsCore column
snapshot so every column it names exists in the archive, and a unit test
asserts the checked-in ``core/prompts/alma_kernel.py`` equals this output and
stays under the token budget (measured with tiktoken).

Usage
-----
    python scripts/gen_alma_kernel.py            # (re)write core/prompts/alma_kernel.py
    python scripts/gen_alma_kernel.py --check    # exit 1 if the checked-in kernel is stale
    python scripts/gen_alma_kernel.py --stdout   # print the kernel text
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = REPO_ROOT / "tests" / "fixtures" / "alma_obscore_columns_2025-12.txt"
OUT_PATH = REPO_ROOT / "core" / "prompts" / "alma_kernel.py"
# Measured with tiktoken o200k_base (the ADQL fragments tokenize densely); the
# hand-written table this replaced measured ~760 tokens by the same encoder.
TOKEN_BUDGET = 400

# Columns the kernel names — every one must exist in the snapshot.
KERNEL_COLUMNS = (
    "member_ous_uid", "asdm_uid", "group_ous_uid", "proposal_id", "frequency", "bandwidth",
    "em_min", "em_max", "t_min", "t_max", "obs_release_date", "velocity_resolution",
    "s_ra", "s_dec", "s_region", "band_list", "frequency_support", "data_rights",
    "qa2_passed", "access_url", "science_observation", "antenna_arrays", "spatial_resolution",
)


def load_snapshot_columns(path: Path = SNAPSHOT) -> dict:
    """{column: unit} from the dated TAP_SCHEMA dump."""
    text = path.read_text(encoding="utf-8")
    columns: dict = {}
    current = None
    for line in text.splitlines():
        if re.match(r"^[a-z_0-9]+$", line.strip()) and not line.startswith(" "):
            current = line.strip()
            columns[current] = ""
        elif current and line.strip().startswith("Type:"):
            unit = line.split("Unit:", 1)[1].strip() if "Unit:" in line else ""
            columns[current] = unit
    return columns


def build_kernel(columns: dict) -> str:
    missing = [c for c in KERNEL_COLUMNS if c not in columns]
    if missing:
        raise SystemExit(f"kernel names columns absent from the snapshot: {missing}")
    units = {c: columns.get(c, "") for c in ("bandwidth", "frequency", "em_min", "velocity_resolution", "t_min")}
    assert units["bandwidth"] == "Hz", units
    assert units["frequency"] == "GHz", units
    assert units["em_min"] == "m", units
    assert units["velocity_resolution"] == "m/s", units
    assert units["t_min"] == "d", units
    date = re.search(r"(\d{4}-\d{2})", SNAPSHOT.name).group(1)
    return f"""ALMA ARCHIVE GUARDRAILS (ivoa.obscore; column snapshot {date}):
- Rows are coverage records (repeat per execution block asdm_uid, field, SPW), NOT observations: datasets = distinct member_ous_uid (MOUS), executions = COUNT(DISTINCT asdm_uid), projects = proposal_id; report all three.
- Units: frequency GHz, bandwidth Hz; em_min/em_max METERS; t_min/t_max MJD; obs_release_date ISO; velocity_resolution m/s; spatial_resolution arcsec.
- Coverage: em_min <= 0.29979/nu_lo AND em_max >= 0.29979/nu_hi, then check frequency_support SPW windows; frequency +/- bandwidth/2 is WRONG.
- Cone: INTERSECTS(CIRCLE('ICRS',ra,dec,r), s_region) = 1 OR CONTAINS(POINT('ICRS',s_ra,s_dec), CIRCLE(...)) = 1 (s_ra/s_dec alone misses mosaics).
- band_list is space-delimited ('5 10' = band-to-band): match tokens. Public: data_rights = 'Public'. Science rows: science_observation = 'T'.
- qa2_passed T/F cannot give PASS/SEMIPASS/FAIL (get_alma_qa2_status). access_url = MOUS DataLink URL (list_alma_files), not a file. No calibrated MS is delivered: restore via scriptForPI under the package CASA version, or ARC/SRDP.
- Resolve names to coordinates and cone-search (search_by_target does); never string-match PI target_name except moving/solar targets, and say so.
- Mosaics, moving/solar, Total Power, polarization, band-to-band, VLBI, restore, TOPO vs LSRK, pipeline history: browse_alma_guidance(topic).
"""


def token_count(text: str) -> int:
    try:
        import tiktoken

        try:
            enc = tiktoken.get_encoding("o200k_base")
        except Exception:
            enc = tiktoken.get_encoding("cl100k_base")
        return len(enc.encode(text))
    except Exception:  # pragma: no cover - tiktoken missing
        return len(text) // 4


def render_module(kernel: str) -> str:
    return (
        '"""GENERATED by scripts/gen_alma_kernel.py from '
        f'{SNAPSHOT.relative_to(REPO_ROOT).as_posix()} — do not edit by hand.\n\n'
        "The always-on ALMA guardrail kernel injected into the system prompt\n"
        "(core/prompts.ALMA_TAP_SCHEMA). Regenerate with\n"
        "``python scripts/gen_alma_kernel.py``; tests assert it is current and under\n"
        f"{TOKEN_BUDGET} tokens.\n"
        '"""\n\n'
        f"ALMA_KERNEL_SNAPSHOT = {SNAPSHOT.name!r}\n"
        f"ALMA_KERNEL_TOKEN_BUDGET = {TOKEN_BUDGET}\n\n"
        f"ALMA_TAP_SCHEMA = {kernel!r}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    kernel = build_kernel(load_snapshot_columns())
    tokens = token_count(kernel)
    if tokens > TOKEN_BUDGET:
        print(f"kernel is {tokens} tokens > budget {TOKEN_BUDGET}", file=sys.stderr)
        return 1
    module = render_module(kernel)
    if args.stdout:
        sys.stdout.write(kernel)
        print(f"\n[{tokens} tokens]", file=sys.stderr)
        return 0
    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if current != module:
            print(f"{OUT_PATH} is stale; run python scripts/gen_alma_kernel.py", file=sys.stderr)
            return 1
        print(f"kernel current ({tokens} tokens)")
        return 0
    OUT_PATH.write_text(module, encoding="utf-8")
    print(f"wrote {OUT_PATH} ({tokens} tokens)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
