"""Export the existing, non-inferred catalog rate card for TypeScript. No HTTP."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from services.model_pricing import CATALOG_UNVERIFIED_PRICES, MODEL_PRICING, PRICING_LAST_VERIFIED


def render() -> str:
    prices = {model: {"provider": provider, "inputPricePerM": rates["input_per_mtok"],
                      "outputPricePerM": rates["output_per_mtok"]}
              for provider, models in MODEL_PRICING.items() for model, rates in models.items()
              if model not in CATALOG_UNVERIFIED_PRICES and "embedding" not in model}
    return ("// Generated by scripts/gen_model_catalog_pricing.py from services/model_pricing.py.\n"
            f"// Existing static rates, last checked {PRICING_LAST_VERIFIED}; unknown models stay unpriced.\n"
            "export interface ModelPrice { provider: string; inputPricePerM: number; outputPricePerM: number }\n"
            "export const MODEL_PRICING: Readonly<Record<string, ModelPrice>> = "
            + json.dumps(prices, indent=2, sort_keys=True) + ";\n\n"
            "export function modelPrice(provider: string, id: string): ModelPrice | undefined {\n"
            "    const exact = MODEL_PRICING[id];\n"
            "    if (exact?.provider === provider) return exact;\n"
            "    const prefix = Object.keys(MODEL_PRICING).filter(key =>\n"
            "        MODEL_PRICING[key].provider === provider && id.startsWith(key) &&\n"
            "        /^[-@:_.]\\d/.test(id.slice(key.length))\n"
            "    ).sort((a, b) => b.length - a.length)[0];\n"
            "    return prefix ? MODEL_PRICING[prefix] : undefined;\n"
            "}\n")


if __name__ == "__main__":
    target = ROOT / "ui-pro/src/lib/pricing.ts"
    if "--check" in sys.argv:
        if not target.exists() or target.read_text(encoding="utf-8") != render():
            raise SystemExit("Catalog pricing is out of date; run scripts/gen_model_catalog_pricing.py")
    else:
        target.write_text(render(), encoding="utf-8")
