// Generated by scripts/gen_model_catalog_pricing.py from services/model_pricing.py.
// Existing static rates, latest verification update 2026-09-30; unknown models stay unpriced.
export interface ModelPrice { provider: string; inputPricePerM: number; outputPricePerM: number }
export const MODEL_PRICING: Readonly<Record<string, ModelPrice>> = {
  "claude-fable-5": {
    "inputPricePerM": 10.0,
    "outputPricePerM": 50.0,
    "provider": "anthropic"
  },
  "claude-haiku-4-5": {
    "inputPricePerM": 1.0,
    "outputPricePerM": 5.0,
    "provider": "anthropic"
  },
  "claude-mythos-5": {
    "inputPricePerM": 10.0,
    "outputPricePerM": 50.0,
    "provider": "anthropic"
  },
  "claude-opus-4-5": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 25.0,
    "provider": "anthropic"
  },
  "claude-opus-4-6": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 25.0,
    "provider": "anthropic"
  },
  "claude-opus-4-7": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 25.0,
    "provider": "anthropic"
  },
  "claude-opus-4-8": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 25.0,
    "provider": "anthropic"
  },
  "claude-opus-5": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 25.0,
    "provider": "anthropic"
  },
  "claude-opus-5-5": {
    "inputPricePerM": 4.0,
    "outputPricePerM": 20.0,
    "provider": "anthropic"
  },
  "claude-sonnet-4-5": {
    "inputPricePerM": 3.0,
    "outputPricePerM": 15.0,
    "provider": "anthropic"
  },
  "claude-sonnet-4-6": {
    "inputPricePerM": 3.0,
    "outputPricePerM": 15.0,
    "provider": "anthropic"
  },
  "claude-sonnet-5": {
    "inputPricePerM": 3.0,
    "outputPricePerM": 15.0,
    "provider": "anthropic"
  },
  "deepseek-chat": {
    "inputPricePerM": 0.27,
    "outputPricePerM": 1.1,
    "provider": "deepseek"
  },
  "deepseek-flash": {
    "inputPricePerM": 0.3,
    "outputPricePerM": 1.2,
    "provider": "deepseek"
  },
  "deepseek-reasoner": {
    "inputPricePerM": 0.55,
    "outputPricePerM": 2.19,
    "provider": "deepseek"
  },
  "deepseek-v4-flash": {
    "inputPricePerM": 0.3,
    "outputPricePerM": 1.2,
    "provider": "deepseek"
  },
  "deepseek-v4-pro": {
    "inputPricePerM": 1.32,
    "outputPricePerM": 3.96,
    "provider": "deepseek"
  },
  "gemini-2.0-flash": {
    "inputPricePerM": 0.1,
    "outputPricePerM": 0.4,
    "provider": "google"
  },
  "gemini-2.5-flash": {
    "inputPricePerM": 0.3,
    "outputPricePerM": 2.5,
    "provider": "google"
  },
  "gemini-2.5-flash-lite": {
    "inputPricePerM": 0.1,
    "outputPricePerM": 0.4,
    "provider": "google"
  },
  "gemini-2.5-pro": {
    "inputPricePerM": 1.25,
    "outputPricePerM": 10.0,
    "provider": "google"
  },
  "gemini-3.1-flash-lite": {
    "inputPricePerM": 0.25,
    "outputPricePerM": 1.5,
    "provider": "google"
  },
  "gemini-3.1-pro-preview": {
    "inputPricePerM": 2.0,
    "outputPricePerM": 12.0,
    "provider": "google"
  },
  "gemini-3.5-flash": {
    "inputPricePerM": 1.5,
    "outputPricePerM": 9.0,
    "provider": "google"
  },
  "gemini-3.5-flash-lite": {
    "inputPricePerM": 0.3,
    "outputPricePerM": 2.5,
    "provider": "google"
  },
  "gemini-3.6-flash": {
    "inputPricePerM": 0.75,
    "outputPricePerM": 3.75,
    "provider": "google"
  },
  "gemini-3.7-flash": {
    "inputPricePerM": 0.75,
    "outputPricePerM": 3.75,
    "provider": "google"
  },
  "gemini-3.8-flash": {
    "inputPricePerM": 0.75,
    "outputPricePerM": 3.75,
    "provider": "google"
  },
  "gpt-4.1": {
    "inputPricePerM": 2.0,
    "outputPricePerM": 8.0,
    "provider": "openai"
  },
  "gpt-4.1-mini": {
    "inputPricePerM": 0.4,
    "outputPricePerM": 1.6,
    "provider": "openai"
  },
  "gpt-4.1-nano": {
    "inputPricePerM": 0.1,
    "outputPricePerM": 0.4,
    "provider": "openai"
  },
  "gpt-4o": {
    "inputPricePerM": 2.5,
    "outputPricePerM": 10.0,
    "provider": "openai"
  },
  "gpt-4o-mini": {
    "inputPricePerM": 0.15,
    "outputPricePerM": 0.6,
    "provider": "openai"
  },
  "gpt-5": {
    "inputPricePerM": 1.25,
    "outputPricePerM": 10.0,
    "provider": "openai"
  },
  "gpt-5-mini": {
    "inputPricePerM": 0.25,
    "outputPricePerM": 2.0,
    "provider": "openai"
  },
  "gpt-5-nano": {
    "inputPricePerM": 0.05,
    "outputPricePerM": 0.4,
    "provider": "openai"
  },
  "gpt-5-pro": {
    "inputPricePerM": 15.0,
    "outputPricePerM": 120.0,
    "provider": "openai"
  },
  "gpt-5.1": {
    "inputPricePerM": 1.25,
    "outputPricePerM": 10.0,
    "provider": "openai"
  },
  "gpt-5.2": {
    "inputPricePerM": 1.75,
    "outputPricePerM": 14.0,
    "provider": "openai"
  },
  "gpt-5.2-pro": {
    "inputPricePerM": 21.0,
    "outputPricePerM": 168.0,
    "provider": "openai"
  },
  "gpt-5.3-codex": {
    "inputPricePerM": 1.75,
    "outputPricePerM": 14.0,
    "provider": "openai"
  },
  "gpt-5.4": {
    "inputPricePerM": 2.5,
    "outputPricePerM": 15.0,
    "provider": "openai"
  },
  "gpt-5.4-mini": {
    "inputPricePerM": 0.75,
    "outputPricePerM": 4.5,
    "provider": "openai"
  },
  "gpt-5.4-nano": {
    "inputPricePerM": 0.2,
    "outputPricePerM": 1.25,
    "provider": "openai"
  },
  "gpt-5.4-pro": {
    "inputPricePerM": 30.0,
    "outputPricePerM": 180.0,
    "provider": "openai"
  },
  "gpt-5.5": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 30.0,
    "provider": "openai"
  },
  "gpt-5.6-luna": {
    "inputPricePerM": 0.2,
    "outputPricePerM": 1.2,
    "provider": "openai"
  },
  "gpt-5.6-sol": {
    "inputPricePerM": 4.0,
    "outputPricePerM": 20.0,
    "provider": "openai"
  },
  "gpt-5.6-terra": {
    "inputPricePerM": 2.0,
    "outputPricePerM": 12.0,
    "provider": "openai"
  },
  "gpt-6-astra": {
    "inputPricePerM": 10.0,
    "outputPricePerM": 50.0,
    "provider": "openai"
  },
  "gpt-6-luna": {
    "inputPricePerM": 0.1,
    "outputPricePerM": 0.5,
    "provider": "openai"
  },
  "gpt-6-sol": {
    "inputPricePerM": 2.0,
    "outputPricePerM": 10.0,
    "provider": "openai"
  },
  "gpt-6.1-sol": {
    "inputPricePerM": 2.0,
    "outputPricePerM": 10.0,
    "provider": "openai"
  },
  "o3": {
    "inputPricePerM": 2.0,
    "outputPricePerM": 8.0,
    "provider": "openai"
  },
  "o3-mini": {
    "inputPricePerM": 1.1,
    "outputPricePerM": 4.4,
    "provider": "openai"
  },
  "o4-mini": {
    "inputPricePerM": 1.1,
    "outputPricePerM": 4.4,
    "provider": "openai"
  }
};

export function modelPrice(provider: string, id: string): ModelPrice | undefined {
    const exact = MODEL_PRICING[id];
    if (exact?.provider === provider) return exact;
    const prefix = Object.keys(MODEL_PRICING).filter(key =>
        MODEL_PRICING[key].provider === provider && id.startsWith(key) &&
        (provider === 'openai' ? /^[-@:_]\d/ : /^[-@:_.]\d/).test(id.slice(key.length))
    ).sort((a, b) => b.length - a.length)[0];
    return prefix ? MODEL_PRICING[prefix] : undefined;
}
