// Generated by scripts/gen_model_catalog_pricing.py from services/model_pricing.py.
// Existing static rates, last checked 2026-07-16; unknown models stay unpriced.
export interface ModelPrice { provider: string; inputPricePerM: number; outputPricePerM: number }
export const MODEL_PRICING: Readonly<Record<string, ModelPrice>> = {
  "claude-fable-5": {
    "inputPricePerM": 10.0,
    "outputPricePerM": 50.0,
    "provider": "anthropic"
  },
  "claude-haiku-4-5": {
    "inputPricePerM": 1.0,
    "outputPricePerM": 5.0,
    "provider": "anthropic"
  },
  "claude-mythos-5": {
    "inputPricePerM": 10.0,
    "outputPricePerM": 50.0,
    "provider": "anthropic"
  },
  "claude-opus-4-5": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 25.0,
    "provider": "anthropic"
  },
  "claude-opus-4-6": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 25.0,
    "provider": "anthropic"
  },
  "claude-opus-4-7": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 25.0,
    "provider": "anthropic"
  },
  "claude-opus-4-8": {
    "inputPricePerM": 5.0,
    "outputPricePerM": 25.0,
    "provider": "anthropic"
  },
  "claude-sonnet-4-5": {
    "inputPricePerM": 3.0,
    "outputPricePerM": 15.0,
    "provider": "anthropic"
  },
  "claude-sonnet-4-6": {
    "inputPricePerM": 3.0,
    "outputPricePerM": 15.0,
    "provider": "anthropic"
  },
  "claude-sonnet-5": {
    "inputPricePerM": 3.0,
    "outputPricePerM": 15.0,
    "provider": "anthropic"
  },
  "deepseek-chat": {
    "inputPricePerM": 0.27,
    "outputPricePerM": 1.1,
    "provider": "deepseek"
  },
  "deepseek-reasoner": {
    "inputPricePerM": 0.55,
    "outputPricePerM": 2.19,
    "provider": "deepseek"
  },
  "gemini-2.0-flash": {
    "inputPricePerM": 0.1,
    "outputPricePerM": 0.4,
    "provider": "google"
  },
  "gemini-2.5-flash": {
    "inputPricePerM": 0.3,
    "outputPricePerM": 2.5,
    "provider": "google"
  },
  "gemini-2.5-pro": {
    "inputPricePerM": 1.25,
    "outputPricePerM": 10.0,
    "provider": "google"
  },
  "gpt-4.1": {
    "inputPricePerM": 2.0,
    "outputPricePerM": 8.0,
    "provider": "openai"
  },
  "gpt-4.1-mini": {
    "inputPricePerM": 0.4,
    "outputPricePerM": 1.6,
    "provider": "openai"
  },
  "gpt-4.1-nano": {
    "inputPricePerM": 0.1,
    "outputPricePerM": 0.4,
    "provider": "openai"
  },
  "gpt-4o": {
    "inputPricePerM": 2.5,
    "outputPricePerM": 10.0,
    "provider": "openai"
  },
  "gpt-4o-mini": {
    "inputPricePerM": 0.15,
    "outputPricePerM": 0.6,
    "provider": "openai"
  },
  "o3": {
    "inputPricePerM": 2.0,
    "outputPricePerM": 8.0,
    "provider": "openai"
  },
  "o3-mini": {
    "inputPricePerM": 1.1,
    "outputPricePerM": 4.4,
    "provider": "openai"
  },
  "o4-mini": {
    "inputPricePerM": 1.1,
    "outputPricePerM": 4.4,
    "provider": "openai"
  }
};

export function modelPrice(provider: string, id: string): ModelPrice | undefined {
    const exact = MODEL_PRICING[id];
    if (exact?.provider === provider) return exact;
    const prefix = Object.keys(MODEL_PRICING).filter(key =>
        MODEL_PRICING[key].provider === provider && id.startsWith(key) &&
        /^[-@:_.]\d/.test(id.slice(key.length))
    ).sort((a, b) => b.length - a.length)[0];
    return prefix ? MODEL_PRICING[prefix] : undefined;
}
